# CodeRabbit Configuration
# Automated code review and analysis

repository:
  enabled: true
  default_branch: main
  include_patterns:
    - "src/**/*"
    - "test/**/*"
    - "*.ts"
    - "*.js"
    - "*.json"
    - "*.yml"
    - "*.yaml"
    - "*.md"
  exclude_patterns:
    - "node_modules/**/*"
    - "dist/**/*"
    - "coverage/**/*"
    - "*.lock"
    - ".git/**/*"

review:
  rules:
    - name: "Security"
      description: "Check for security vulnerabilities"
      enabled: true
      severity: "high"
    
    - name: "Code Quality"
      description: "Ensure code quality standards"
      enabled: true
      severity: "medium"

analysis:
  depth: "medium"
  language_specific:
    typescript:
      enabled: true
      strict: true
    javascript:
      enabled: true
    json:
      enabled: true

notifications:
  enabled: true
  channels:
    - "github"
    - "slack"

project_settings:
  auto_merge: false
  require_reviews: 1
  merge_strategy: "squash" 