name: PR Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ development ]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '10.12.3'

jobs:
  pr-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Check bundle size
        run: |
          echo "Checking bundle size..."
          pnpm build
          du -sh dist/
      
      - name: Check for console.log statements
        run: |
          echo "Checking for console.log statements..."
          if grep -r "console.log" src/ --include="*.ts" --include="*.js"; then
            echo "Warning: console.log statements found in source code"
            exit 1
          fi
      
      - name: Check for TODO comments
        run: |
          echo "Checking for TODO comments..."
          if grep -r "TODO" src/ --include="*.ts" --include="*.js"; then
            echo "Warning: TODO comments found in source code"
            exit 1
          fi

  code-quality:
    runs-on: ubuntu-latest
    needs: pr-analysis
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: TypeScript compilation check
        run: pnpm build
      
      - name: Check for unused dependencies
        run: |
          echo "Checking for unused dependencies..."
          pnpm depcheck
      
      - name: Check for circular dependencies
        run: |
          echo "Checking for circular dependencies..."
          pnpm madge --circular src/
      
      - name: Run ESLint
        run: pnpm lint
      
      - name: Check Prettier formatting
        run: pnpm format:check
      
      - name: Run tests
        run: pnpm test 