name: Release Documentation

on:
  push:
    branches: [ main ]

jobs:
  zapier-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send release data to Zapier
        env:
          ZAP_URL: https://hooks.zapier.com/hooks/catch/24198158/u6azlzw/
        run: |
          curl -X POST "$ZAP_URL" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg repo "${{ github.repository }}" \
              --arg branch "${{ github.ref_name }}" \
              --arg sha "${{ github.sha }}" \
              --arg actor "${{ github.actor }}" \
              --arg commit_url "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" \
              --arg commit_message "${{ github.event.head_commit.message }}" \
              --arg timestamp "${{ github.event.head_commit.timestamp }}" \
              --arg author_name "${{ github.event.head_commit.author.name }}" \
              --arg author_email "${{ github.event.head_commit.author.email }}" \
              '{
                "repo": $repo,
                "branch": $branch,
                "sha": $sha,
                "actor": $actor,
                "commit_url": $commit_url,
                "commit_message": $commit_message,
                "timestamp": $timestamp,
                "author_name": $author_name,
                "author_email": $author_email,
                "event_type": "push_to_main",
                "triggered_at": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
              }')"
        
      - name: Verify webhook response
        run: |
          echo "✅ Webhook sent successfully to Zapier"
          echo "📊 Repository: ${{ github.repository }}"
          echo "🌿 Branch: ${{ github.ref_name }}"
          echo "🔗 Commit: ${{ github.sha }}"
          echo "👤 Author: ${{ github.actor }}" 